django_school/classroom/urls.py
from django.urls import include, path

from .views import classroom, students, teachers
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('', classroom.home, name='home'),

    path('students/', include(([
        path('submit_details', students.StudentDetailsView.as_view(),
             name='submit_details'),
        path('profile/<str:name>', students.student_attendance_detail,
             name='student_details')
     ], 'classroom'), namespace='students')),

    path('teachers/', include(([
        path('',
             TemplateView.as_view(
              template_name='classroom/teachers/dashboard.html'),
             name='dashboard'),
        path('take_attendance', teachers.AttendanceView.as_view(),
             name='attendance'),
        path('taken_attendance_info/<int:pk>', teachers.taken_attendance_info,
             name='taken_attendance_info'),
        path('all_attendance_info', teachers.all_attendance_info,
             name='all_attendance_info'),
        path('download_attendance', teachers.download_attendance,
             name='download_csv'),
        path('students_list', teachers.students_list, name='students_list')
     ], 'classroom'), namespace='teachers')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

django_school/django_school/urls.py
from django.urls import include, path
from django.contrib import admin
from classroom.views import classroom, students, teachers

urlpatterns = [
    path('', include('classroom.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
]

django_school/classroom/models.py
import os
from django.contrib.auth.models import AbstractUser
from django.db import models
import datetime
from facenet.algo import input_embeddings, recognize_faces_in_cam, TrainImage
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import get_object_or_404
today = datetime.datetime.today()


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)


def teacher_directory_path(instance, filename):
    file_type = "." + filename.split('.')[-1]
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'attendance_images/{0}/{1}/{2}/{3}/{4}'.format(
        instance.user.username, today.year, today.month, today.day,
        instance.branch + "_" + str(instance.semester) + file_type)


def student_directory_path(instance, filename):
    file_type = "." + filename.split('.')[-1]
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'embeddings/{0}'.format(
        instance.user.username + file_type)


BRANCH_CHOICES = [
        ('Information_Technology', 'Information_Technology'),
        ('CSE', 'CSE'),
        ('Electronics_and_Electrical_Engineering',
         'Electronics_and_Electrical_Engineering'),
        ('Mining', 'Mining'),
    ]


class Attendance(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    branch = models.CharField(max_length=50, choices=BRANCH_CHOICES)
    semester = models.IntegerField()
    image = models.ImageField(upload_to=teacher_directory_path)
    count = models.IntegerField(default=0)
    date = models.DateField(default=today)
    count_added = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username + self.branch


class StudentDetails(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    branch = models.CharField(max_length=50, choices=BRANCH_CHOICES)
    semester = models.IntegerField()
    image = models.ImageField(upload_to=student_directory_path)

    def __str__(self):
        return self.user.username


class AttendanceRecord(models.Model):
    teacher = models.ForeignKey(User, on_delete=models.CASCADE)
    student = models.ForeignKey(StudentDetails, on_delete=models.CASCADE)
    branch = models.CharField(max_length=50, choices=BRANCH_CHOICES)
    semester = models.IntegerField()
    date = models.DateField()
    subject = models.CharField(max_length=50)

    def __str__(self):
        return self.student.user.username


@receiver(post_save, sender=Attendance, dispatch_uid="pass_image")
def pass_image_to_neural_net(sender, instance, **kwargs):
    image_url = instance.image.url[1::]
    #attendance_data = {'record': ['harsh', 'manav', 'tandon'], 'count': 50 }
    attendance_data = recognize_faces_in_cam(input_embeddings, image_url)
    record = attendance_data['record']
    teacher = instance.user
    branch = instance.branch
    semester = instance.semester
    subject = instance.subject

    if not instance.count_added:

        q = Attendance.objects.get(id=instance.id)
        q.count = attendance_data['count']
        q.count_added = True
        q.save()
        return
    print("Pass image to neural net:The detected identity in pic uploaded by teacher are = ", record)
    for i in record:
        id = i.split('_')[-1]
        print(id)
        print(i)
        student = get_object_or_404(StudentDetails, pk=int(id))# StudentDetails.objects.get(user__username=i)
        r = AttendanceRecord(teacher=teacher, subject=subject, student=student, semester=semester, branch=branch, date=today)
        r.save()


@receiver(post_save, sender=StudentDetails, dispatch_uid="train_image")
def train_image(sender, instance, **kwargs):
    url = instance.image.url[1::]
    print('url=', url)
    TrainImage(url, instance.user.username + "_" + str(instance.id))

django_school/classroom/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError

from .models import User, Attendance, StudentDetails


class TeacherSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_teacher = True
        if commit:
            user.save()
        return user


class StudentSignUpForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        return user


class AttendanceForm(forms.ModelForm):
    class Meta:
        model = Attendance
        fields = ('branch', 'semester', 'image', 'subject')


class StudentDetailsForm(forms.ModelForm):
    class Meta:
        model = StudentDetails
        fields = ('branch', 'semester', 'image')


BRANCH_CHOICES = [('', '---------')] + [
        ('Information_Technology', 'Information_Technology'),
        ('CSE', 'CSE'),
        ('Electronics_and_Electrical_Engineering',
         'Electronics_and_Electrical_Engineering'),
        ('Mining', 'Mining'),
    ]


class DownloadCsv(forms.Form):
    year = forms.IntegerField(min_value=1950, max_value=2500)
    month = forms.IntegerField(min_value=1, max_value=12)
    date = forms.IntegerField(min_value=1, max_value=31)
    semester = forms.IntegerField(min_value=1, max_value=12)
    branch = forms.ChoiceField(choices=BRANCH_CHOICES)


class FilterForm(forms.Form):

    branch = forms.ChoiceField(choices=BRANCH_CHOICES, required=False)
    semester = forms.IntegerField(min_value=1, max_value=12, required=False)

django_school/classroom/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView

from django.template.defaulttags import register


@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:dashboard')
        else:
            return redirect('students:student_details',
                            name=request.user.username)
    return render(request, 'classroom/home.html')

django_school/classroom/views/students.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView
from django.http import HttpResponse
from ..decorators import student_required
from ..forms import (StudentSignUpForm, StudentDetailsForm)
from ..models import User, StudentDetails,  AttendanceRecord, Attendance
from collections import Counter
from math import floor


class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('students:submit_details')


@method_decorator([login_required, student_required], name='dispatch')
class StudentDetailsView(CreateView):
    model = StudentDetails
    form_class = StudentDetailsForm
    template_name = "classroom/students/student_details.html"

    def get_context_data(self, **kwargs):
        kwargs['success'] = "Congratulations ! You are now registered in the college."
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save(commit=False)
        user.user = self.request.user
        user.save()
        return redirect('students:student_details',
                        name=self.request.user.username)


def student_statistics(obj):
    obj_subject = []
    teacher_list = {}

    for i in obj:
        obj_subject.append(i.subject)
        teacher_list[i.subject] = i.teacher.username

    context = Counter(obj_subject)
    total_classes_context = {}
    print(teacher_list)

    for subject in context.keys():
        total = Attendance.objects.filter(subject=subject).count()
        attendance_percentage = floor((context[subject]/total)*100)
        total_classes_context[subject] = [context[subject], total,
                                          attendance_percentage,
                                          teacher_list[subject]]
    return total_classes_context


def student_attendance_detail(request, name):
    student = name
    print(name)
    obj = AttendanceRecord.objects.filter(
                    student__user__username=student)
    student_info = StudentDetails.objects.get(user__username=student)
    total_classes_context = student_statistics(obj)

    try:
        return render(request, 'classroom/students/student_info.html',
                      {'total_classes': total_classes_context,
                       'info': student_info})
    except:
        return render(request, 'classroom/students/student_info.html',
                      {'error': "No such student ID exists."})

django_school/classroom/views/teachers.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView
from django.http import HttpResponse
from ..decorators import teacher_required
from ..forms import TeacherSignUpForm, AttendanceForm, DownloadCsv, FilterForm
from ..models import User, Attendance, AttendanceRecord, StudentDetails
from django.utils.encoding import smart_str
import os
import csv
from classroom.views.students import student_statistics


class TeacherSignUpView(CreateView):
    model = User
    form_class = TeacherSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect("teachers:dashboard")


@method_decorator([login_required, teacher_required], name='dispatch')
class AttendanceView(CreateView):
    model = Attendance
    form_class = AttendanceForm
    template_name = "classroom/teachers/attendance_details.html"

    def form_valid(self, form):

        user = form.save(commit=False)
        user.user = self.request.user
        user.save()
        return redirect("teachers:taken_attendance_info", pk=user.id)


@login_required
@teacher_required
def download_attendance(request):
    form = DownloadCsv()
    if request.method == "POST":
        form = DownloadCsv(request.POST)
        if form.is_valid():
            user = request.user.username
            day = form.cleaned_data.get('date')
            year = form.cleaned_data.get('year')
            month = form.cleaned_data.get('month')
            date = str(year) + "-" + str(month) + "-" + str(day)
            semester = form.cleaned_data.get('semester')
            branch = form.cleaned_data.get('branch')
            obj = AttendanceRecord.objects.filter(
                teacher__username=user, date=date, branch=branch,
                semester=semester)

            path_to_file = str(date) + "/" + branch + "_" + str(semester) + ".csv"

            response = HttpResponse(content_type='text/csv')

            response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(path_to_file)

            writer = csv.writer(response)
            writer.writerow(["List of Students present"])
            for i in obj:
                writer.writerow([i])
            return response
    return render(request, 'classroom/teachers/download_csv.html',
                  {'form': form})


def students_list(request):

    form = FilterForm(request.GET)

    if 'branch' and 'semester' in request.GET:
        if request.GET['branch'] != '' and request.GET['semester'] != '':
            students = StudentDetails.objects.filter(
                branch=request.GET['branch'], semester=request.GET['semester'])
        elif request.GET['branch'] != '':
            students = StudentDetails.objects.filter(
                branch=request.GET['branch'])
        elif request.GET['semester']:
            students = StudentDetails.objects.filter(
                        semester=request.GET['semester'])
        else:
            students = StudentDetails.objects.all()

    elif len(request.GET) != 0:
        return render(request, "404.html")

    else:
        students = StudentDetails.objects.all()
    status_dict = {}
    for student in students:
        status_dict[student.user.username] = is_regular(student.user.username)
    print(status_dict)

    return render(request, 'classroom/teachers/students_list.html',
                  {'students': students, 'form': form,
                   'status': status_dict})


def is_regular(student):
    obj = AttendanceRecord.objects.filter(
                    student__user__username=student)
    total_classes = student_statistics(obj)
    min = 50
    status = 'Regular'
    for values in total_classes.values():
        if values[2] < min:
            status = 'Not Regular'
            break
    return status


def taken_attendance_info(request, pk):
    attendance_obj = get_object_or_404(Attendance, pk=pk)
    return render(request, 'classroom/teachers/taken_attendance_info.html',
                  {'attendance_info': attendance_obj})


def all_attendance_info(request):
    attendance_obj = Attendance.objects.filter(user=request.user).order_by('-date')
    return render(request, 'classroom/teachers/all_attendance_info.html',
                  {'attendance_info': attendance_obj})

django_school/classroom/templates/classroom/teachers/all_attendance_info.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-md-12 col-sm-10 col-12">
        <table class="table table-hover table-borderless table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Date(Click for info)</th>
                    <th scope="col">Branch</th>
                    <th scope="col">Semester</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Download</th>
                </tr>
            </thead>
            <tbody>
            {% for attendance in attendance_info  %}
                    <tr>
                        <th scope="row">{{ forloop.counter}}</th>
                        <td><a href="{% url 'teachers:taken_attendance_info' pk=attendance.pk %}">
                            @{{attendance.date}}</a>
                        </td>
                        <td>{{ attendance.branch }}</td>
                        <td>{{ attendance.semester }}</td>
                        <td>{{ attendance.subject }}</td>
                        <td>
                    <form method="post" action="{% url 'teachers:download_csv' %}">
                        {% csrf_token %}
                        
                        <input type='hidden' value='{{attendance.date.year}}' name='year'>
                        <input type='hidden' value='{{attendance.date.month}}' name='month'>
                        <input type='hidden' value='{{attendance.date.day}}' name='date'>
                        <input type='hidden' value='{{attendance.branch}}' name='branch'>
                        <input type='hidden' value='{{attendance.semester}}' name='semester'>
                        <button type="submit" class="btn btn-warning">Download Attendance</button>
                    </form></td>
                    </tr>
            {% empty %}
                <div class="alert alert-danger">
                    Sorry no students in the respective Branch or Semester
                </div>
            {% endfor %}
            </tbody>
        </table>
    </div>
    
  </div>
{% endblock %}

django_school/classroom/templates/classroom/teachers/attendance_details.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-md-8 col-sm-10 col-12">
      <h2>Take attendance</h2>
      <form method="post" novalidate enctype="multipart/form-data">
        {% csrf_token %}

        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Submit</button>
      </form>
    </div>
  </div>
{% endblock %}

django_school/classroom/templates/classroom/teachers/dashboard.html
{% extends "base.html" %}

{% block content %}

<div class="row">
<div class="col-md-6">
<div class="jumbotron">
  <h1 class="display-4">Easy Attendance</h1>
  <p class="lead">Take easily attendance of your class with good accuracy and absolutely no chance of proxy. Move on from traditional pen paper attendance method.
 </p>
  <hr class="my-4">
  <p>Just enter details of class and click and upload the picture of classroom.</p>
  <a class="btn btn-success btn-lg" href="{% url 'teachers:attendance'  %}" role="button">Take attendance</a>
</div>
</div>

<div class="col-md-6">
<div class="jumbotron">
  <h1 class="display-4">Attendance Record</h1>
  <p class="lead">All the attendance are managed and stored in database. Download the Attedance in a clear csv format and also check the class image of that day.</p>
  <hr class="my-4">
  <p>Enter the details of class to download the attendance record.</p>
  <a class="btn btn-warning btn-lg" href="{% url 'teachers:download_csv'  %}" role="button">Download Attendance</a>
</div>
</div>
</div>

<div class="row">

    <div class="col-md-6">
    <div class="jumbotron">
    <h1 class="display-4">Check students performance</h1>
    <p class="lead">Manager does all the hardwork of teachers like all necessary caclulations
     on records. See easily attendance of your 
     students and their overall profile with absolutely no chance of miscalculations
    </p>
    <hr class="my-4">

    <a class="btn btn-info btn-lg" href="{% url 'teachers:students_list'  %}" role="button">Go to Students List</a>
    </div>
    </div>

    <div class="col-md-6">
    <div class="jumbotron">
    <h1 class="display-4">Attedance Record</h1>
    <p class="lead">See all the attendance in one place. Also get full information about a particular attendance .
    </p>
    <hr class="my-4">

    <a class="btn btn-dark btn-lg" href="{% url 'teachers:all_attendance_info'  %}" role="button">Go to Records</a>
    </div>
    </div>

</div>


{% endblock  %}

django_school/classroom/templates/classroom/teachers/download_csv.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-md-8 col-sm-10 col-12">
      <h2>Download attendance record</h2>
      <form method="post" novalidate enctype="multipart/form-data">
        {% csrf_token %}

        {{ form|crispy }}
        <button type="submit" class="btn btn-warning">Download</button>
      </form>
    </div>
  </div>
{% endblock %}

django_school/classroom/templates/classroom/teachers/students_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-md-8 col-sm-10 col-12">
        <table class="table table-hover table-borderless">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">student's handle</th>
                    <th scope="col">branch</th>
                    <th scope="col">sem</th>
                    <th scope="col">status</th>
                </tr>
            </thead>
            <tbody>
            {% for student in students  %}
                {% if status|get_item:student.user.username == "Not Regular"  %}
                    <tr class="table-danger">
                {% else %}
                    <tr class="table-success">
                {% endif %}
                        <th scope="row">{{ forloop.counter}}</th>
                        <td><a href="{% url 'students:student_details' name=student.user.username %}">
                            @{{student.user.username}}</a>
                        </td>
                        <td>{{ student.branch }}</td>
                        <td>{{ student.semester }}</td>
                        <td>{{ status|get_item:student.user.username }}</td>
                    </tr>
            {% empty %}
                <div class="alert alert-danger">
                    Sorry no students in the respective Branch or Semester
                </div>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-md-4 col-sm-10 col-12">
        <h2>Filter</h2>
            <form method="get" novalidate>
                {{ form|crispy }}
                <button type="submit" class="btn btn-secondary">Filter list</button>
            </form>
    </div>
  </div>
{% endblock %}

django_school/classroom/templates/classroom/teachers/taken_attendance_info.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-center">
        <div class="col-md-10 col-sm-10 col-12 align-self-center">
            <h1 class="display-4">Attendance Information
            </h1>
            <br><br>
            
            <p class="lead"><strong>Teacher's handle :  </strong>@{{attendance_info.user.username}}</p>
            <p class="lead"><strong>Branch :  </strong>{{attendance_info.branch}}</p>
            <p class="lead"><strong>Semester :  </strong>{{attendance_info.semester}}</p>
            <p class="lead"><strong>Subject :  </strong>{{attendance_info.subject}}</p>
            <p class="lead"><strong>Date :  </strong>{{attendance_info.date}}</p>
            <p class="lead"><strong>Number of students : </strong>{{attendance_info.count}}</p>
            <p class="lead"><strong>Image captured </strong></p>
            <img src="{{attendance_info.image.url}}" class="img-fluid img-thumbnail"
             style="width: 65vw;" />

             <hr>
             <div class="alert alert-info">
                If all the faces are not detected please <strong><a href="{% url 'teachers:attendance' %}">try again</a></strong> from different angle.
            </div>

            <form method="post" action="{% url 'teachers:download_csv' %}">
                {% csrf_token %}
                
                <input type='hidden' value='{{attendance_info.date.year}}' name='year'>
                <input type='hidden' value='{{attendance_info.date.month}}' name='month'>
                <input type='hidden' value='{{attendance_info.date.day}}' name='date'>
                <input type='hidden' value='{{attendance_info.branch}}' name='branch'>
                <input type='hidden' value='{{attendance_info.semester}}' name='semester'>
                <button type="submit" class="btn btn-warning">Download Attendance in CSV</button>
            </form>
        </div>
    </div>
{% endblock  %}